(function() {
  "use strict";
  var isInSubfolder = window.location.pathname.indexOf("/admin/") !== -1 || window.location.pathname.indexOf("/ratgeber/") !== -1;
  var logoPath = isInSubfolder ? "../blitz_leihen_logo.webp" : "blitz_leihen_logo.webp";
  var rootPath = isInSubfolder ? "../" : "";
  var LOADER_HTML = [
    '<div id="pageLoader" class="page-loader" role="status" aria-label="Seite l\xE4dt...">',
    '  <div class="page-loader__inner">',
    '    <div class="page-loader__ring"></div>',
    '    <img src="' + logoPath + '" alt="Blitz Leihen" class="page-loader__logo-img">',
    "  </div>",
    "</div>"
  ].join("\n");
  var HEADER_HTML = [
    '<header class="site-header" id="siteHeader" role="banner">',
    '  <div class="header-inner">',
    "",
    "    <!-- Logo Blitz Leihen -->",
    '    <a href="' + rootPath + 'index.html" class="site-logo" aria-label="Blitz Leihen \u2013 Startseite">',
    '      <img src="' + logoPath + '" alt="Blitz Leihen" class="site-logo__img" width="160" height="50">',
    "    </a>",
    "",
    "    <!-- Navigation Desktop -->",
    '    <nav class="nav-desktop" role="navigation" aria-label="Hauptnavigation">',
    '      <a href="' + rootPath + 'index.html"      class="nav-desktop__link">Startseite</a>',
    '      <a href="' + rootPath + 'kredite.html"    class="nav-desktop__link">Kredite</a>',
    '      <a href="' + rootPath + 'immobilien.html" class="nav-desktop__link">Immobilienfinanzierung</a>',
    '      <a href="' + rootPath + 'simulation.html" class="nav-desktop__link">Kreditrechner</a>',
    '      <a href="' + rootPath + 'ratgeber.html"   class="nav-desktop__link">Ratgeber</a>',
    '      <a href="' + rootPath + 'ueber-uns.html"  class="nav-desktop__link">\xDCber uns</a>',
    '      <a href="' + rootPath + 'kontakt.html"    class="nav-desktop__link">Kontakt</a>',
    '      <a href="' + rootPath + 'kreditantrag.html" class="nav-desktop__link nav-desktop__cta">Kreditantrag stellen</a>',
    "    </nav>",
    "",
    "    <!-- Bouton Hamburger (mobile/tablette) -->",
    '    <button class="nav-toggle" id="navToggle" aria-label="Men\xFC \xF6ffnen" aria-expanded="false" aria-controls="navMobile">',
    '      <span class="nav-toggle__bar"></span>',
    '      <span class="nav-toggle__bar"></span>',
    '      <span class="nav-toggle__bar"></span>',
    "    </button>",
    "  </div>",
    "</header>",
    "",
    "<!-- Overlay derri\xE8re la sidebar mobile -->",
    '<div class="nav-overlay" id="navOverlay" aria-hidden="true"></div>',
    "",
    "<!-- Sidebar Mobile (s'ouvre de droite vers gauche) -->",
    '<nav class="nav-mobile" id="navMobile" role="navigation" aria-label="Mobile Navigation" aria-hidden="true">',
    "",
    "  <!-- En-t\xEAte de la sidebar -->",
    '  <div class="nav-mobile__header">',
    '    <a href="' + rootPath + 'index.html" class="site-logo nav-mobile__logo" aria-label="Blitz Leihen">',
    '      <img src="' + logoPath + '" alt="Blitz Leihen" class="site-logo__img" width="130" height="40">',
    "    </a>",
    '    <button class="nav-mobile__close" id="navClose" aria-label="Men\xFC schlie\xDFen">\xD7</button>',
    "  </div>",
    "",
    "  <!-- Corps de la sidebar : liens de navigation -->",
    '  <div class="nav-mobile__body">',
    '    <a href="' + rootPath + 'index.html"      class="nav-mobile__link">',
    "      <span>\u{1F3E0} Startseite</span>",
    '      <span class="nav-mobile__link-arrow">\u203A</span>',
    "    </a>",
    '    <a href="' + rootPath + 'kredite.html"    class="nav-mobile__link">',
    "      <span>\u{1F4B6} Kredite</span>",
    '      <span class="nav-mobile__link-arrow">\u203A</span>',
    "    </a>",
    '    <a href="' + rootPath + 'immobilien.html" class="nav-mobile__link">',
    "      <span>\u{1F3E0} Immobilienfinanzierung</span>",
    '      <span class="nav-mobile__link-arrow">\u203A</span>',
    "    </a>",
    '    <a href="' + rootPath + 'simulation.html" class="nav-mobile__link">',
    "      <span>\u{1F9EE} Kreditrechner</span>",
    '      <span class="nav-mobile__link-arrow">\u203A</span>',
    "    </a>",
    '    <a href="' + rootPath + 'zinssatz.html"   class="nav-mobile__link">',
    "      <span>\u{1F4D6} Wie wird Ihr Zinssatz berechnet?</span>",
    '      <span class="nav-mobile__link-arrow">\u203A</span>',
    "    </a>",
    '    <a href="' + rootPath + 'ratgeber.html"   class="nav-mobile__link">',
    "      <span>\u{1F4F0} Ratgeber</span>",
    '      <span class="nav-mobile__link-arrow">\u203A</span>',
    "    </a>",
    '    <a href="' + rootPath + 'ueber-uns.html"  class="nav-mobile__link">',
    "      <span>\u{1F465} \xDCber uns</span>",
    '      <span class="nav-mobile__link-arrow">\u203A</span>',
    "    </a>",
    '    <a href="' + rootPath + 'kontakt.html"    class="nav-mobile__link">',
    "      <span>\u2709 Kontakt</span>",
    '      <span class="nav-mobile__link-arrow">\u203A</span>',
    "    </a>",
    "  </div>",
    "",
    "  <!-- Pied de la sidebar : CTA -->",
    '  <div class="nav-mobile__footer">',
    '    <a href="' + rootPath + 'kreditantrag.html" class="btn btn-accent">\u26A1 Jetzt Kredit beantragen</a>',
    "  </div>",
    "</nav>"
  ].join("\n");
  var FOOTER_HTML = [
    '<footer class="site-footer" role="contentinfo">',
    "  <!-- Fond photo 100% statique (CSS pur, voir css/bg-effects.css) -->",
    '  <div class="footer-top">',
    "",
    "    <!-- Colonne : marque -->",
    '    <div class="footer-brand">',
    '      <a href="' + rootPath + 'index.html" class="site-logo">',
    '        <img src="' + logoPath + '" alt="Blitz Leihen" class="site-logo__img" width="160" height="50" loading="lazy">',
    "      </a>",
    '      <p class="footer-brand__desc">',
    "        Blitz Leihen ist Ihr vertrauensw\xFCrdiger Finanzpartner f\xFCr Privat- und Immobilienkredite in Deutschland. Schnell, transparent und fair.",
    "      </p>",
    '      <div class="footer-badges">',
    '        <span class="footer-badge">\u{1F512} SSL-verschl\xFCsselt</span>',
    '        <span class="footer-badge">\u{1F1E9}\u{1F1EA} In Deutschland ans\xE4ssig</span>',
    '        <span class="footer-badge">\u26A1 48h Auszahlung</span>',
    "      </div>",
    "    </div>",
    "",
    "    <!-- Colonne : Produkte -->",
    '    <div class="footer-col">',
    '      <h3 class="footer-col__title">Unsere Produkte</h3>',
    '      <ul class="footer-col__links">',
    '        <li><a href="' + rootPath + 'kreditantrag.html"          class="footer-col__link">\u26A1 Kreditantrag stellen</a></li>',
    '        <li><a href="' + rootPath + 'kredite.html#privatkredit"   class="footer-col__link">Privatkredit</a></li>',
    '        <li><a href="' + rootPath + 'immobilien.html"             class="footer-col__link">Immobilienkredit</a></li>',
    '        <li><a href="' + rootPath + 'kredite.html#autokredit"     class="footer-col__link">Autofinanzierung</a></li>',
    '        <li><a href="' + rootPath + 'kredite.html#renovierung"    class="footer-col__link">Renovierungskredit</a></li>',
    '        <li><a href="' + rootPath + 'kredite.html#hypothek"       class="footer-col__link">Hypothekenkredit</a></li>',
    '        <li><a href="' + rootPath + 'kredite.html#umschuldung"    class="footer-col__link">Umschuldung</a></li>',
    '        <li><a href="' + rootPath + 'simulation.html"             class="footer-col__link">\u{1F9EE} Kreditrechner</a></li>',
    '        <li><a href="' + rootPath + 'zinssatz.html"               class="footer-col__link">\u{1F4D6} Wie wird Ihr Zinssatz berechnet?</a></li>',
    "      </ul>",
    "    </div>",
    "",
    "    <!-- Colonne : Unternehmen -->",
    '    <div class="footer-col">',
    '      <h3 class="footer-col__title">Unternehmen</h3>',
    '      <ul class="footer-col__links">',
    '        <li><a href="' + rootPath + 'ueber-uns.html"  class="footer-col__link">\xDCber uns</a></li>',
    '        <li><a href="' + rootPath + 'ratgeber.html"   class="footer-col__link">Ratgeber</a></li>',
    '        <li><a href="' + rootPath + 'faq.html"        class="footer-col__link">H\xE4ufige Fragen (FAQ)</a></li>',
    '        <li><a href="' + rootPath + 'kundenstimmen.html" class="footer-col__link">Kundenstimmen</a></li>',
    '        <li><a href="' + rootPath + 'kontakt.html"    class="footer-col__link">Kontakt</a></li>',
    '        <li><a href="' + rootPath + 'ueber-uns.html#team" class="footer-col__link">Unser Team</a></li>',
    '        <li><a href="' + rootPath + 'ueber-uns.html#karriere" class="footer-col__link">Karriere</a></li>',
    "      </ul>",
    "    </div>",
    "",
    "    <!-- Colonne : Rechtliches -->",
    '    <div class="footer-col">',
    '      <h3 class="footer-col__title">Rechtliches</h3>',
    '      <ul class="footer-col__links">',
    '        <li><a href="' + rootPath + 'datenschutz.html" class="footer-col__link">Datenschutzerkl\xE4rung</a></li>',
    '        <li><a href="' + rootPath + 'agb.html"          class="footer-col__link">AGB</a></li>',
    '        <li><a href="' + rootPath + 'impressum.html"    class="footer-col__link">Impressum</a></li>',
    '        <li><a href="' + rootPath + 'kontakt.html"      class="footer-col__link">Widerruf</a></li>',
    "      </ul>",
    "      <!-- Infos contact rapides -->",
    '      <div style="margin-top: 1.5rem;">',
    '        <p style="font-size:0.8rem; color:rgba(255,255,255,0.45); line-height:1.8;">',
    '          \u2709 <span style="font-family:var(--font-mono);">info@blitzleihen.com</span><br>',
    '          \u{1F4DE} <span style="font-family:var(--font-mono);">+49 (0) 69 1200 656 0</span><br>',
    "          Mo\u2013Fr: 08:00\u201318:00 Uhr",
    "        </p>",
    "      </div>",
    "    </div>",
    "  </div>",
    "",
    '  <hr class="footer-divider">',
    "",
    '  <div class="footer-bottom">',
    '    <p class="footer-bottom__copy">',
    "      &copy; 2025 Blitz Leihen GmbH. Alle Rechte vorbehalten. Kreditvermittlung unterliegt der BaFin-Regulierung.",
    "    </p>",
    '    <nav class="footer-bottom__links" aria-label="Rechtliche Links">',
    '      <a href="' + rootPath + 'impressum.html"   class="footer-bottom__link">Impressum</a>',
    '      <a href="' + rootPath + 'datenschutz.html" class="footer-bottom__link">Datenschutz</a>',
    '      <a href="' + rootPath + 'agb.html"          class="footer-bottom__link">AGB</a>',
    "    </nav>",
    "  </div>",
    "</footer>",
    "",
    "<!-- Bouton retour en haut de page -->",
    '<button id="backToTop" aria-label="Nach oben scrollen" title="Nach oben">\u2191</button>'
  ].join("\n");
  function inject(placeholderId, html) {
    var el = document.getElementById(placeholderId);
    if (!el) return false;
    el.outerHTML = html;
    return true;
  }
  function init() {
    inject("pageLoaderPlaceholder", LOADER_HTML);
    inject("siteHeaderPlaceholder", HEADER_HTML);
    inject("siteFooterPlaceholder", FOOTER_HTML);
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
